# Generated by Django 4.2.11 on 2024-04-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('transitions_from', models.ManyToManyField(blank=True, related_name='transitions', to='apptracker.status')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('pay', models.IntegerField()),
                ('desc', models.TextField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('exployment_type', models.CharField(choices=[('R', 'Remote'), ('H', 'Hybrid'), ('IO', 'InOffice'), ('C', 'Contract')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptracker.status')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
