# Generated by Django 4.2.11 on 2024-04-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
